/* eslint-disable quote-props, no-param-reassign */

export default {
  'alamogordonews': {
    'displayName': 'Alamogordo Daily News',
    'baseUrl': 'alamogordonews.com',
    'hostName': 'alamogordonews',
    'region': 'Southwest',
  },
  'app': {
    'displayName': 'Asbury Park Press',
    'baseUrl': 'app.com',
    'hostName': 'app',
    'region': 'New Jersey',
  },
  'argusleader': {
    'displayName': 'Argus Leader',
    'baseUrl': 'argusleader.com',
    'hostName': 'argusleader',
    'region': 'Plains',
  },
  'azcentral': {
    'displayName': 'azcentral',
    'baseUrl': 'azcentral.com',
    'hostName': 'azcentral',
    'region': 'Southwest',
  },
  'battlecreekenquirer': {
    'displayName': 'Battle Creek Enquirer',
    'baseUrl': 'battlecreekenquirer.com',
    'hostName': 'battlecreekenquirer',
    'region': 'Midwest',
  },
  'baxterbulletin': {
    'displayName': 'The Baxter Bulletin',
    'baseUrl': 'baxterbulletin.com',
    'hostName': 'baxterbulletin',
    'region': 'Plains',
  },
  'blackmountainnews': {
    'displayName': 'Black Mountain News',
    'baseUrl': 'blackmountainnews.com',
    'hostName': 'blackmountainnews',
    'region': 'Southeast',
  },
  'bucyrustelegraphforum': {
    'displayName': 'Bucyrus Telegraph',
    'baseUrl': 'bucyrustelegraphforum.com',
    'hostName': 'bucyrustelegraphforum',
    'region': 'Ohio',
  },
  'burlingtonfreepress': {
    'displayName': 'Burlington Free Press',
    'baseUrl': 'burlingtonfreepress.com',
    'hostName': 'burlingtonfreepress',
    'region': 'Northeast',
  },
  'caller': {
    'displayName': 'Corpus Christi Caller-Times',
    'baseUrl': 'caller.com',
    'hostName': 'caller',
    'region': 'Texas',
  },
  'centralfloridafuture': {
    'displayName': 'Central Florida Future',
    'baseUrl': 'centralfloridafuture.com',
    'hostName': 'centralfloridafuture',
    'region': 'Florida',
  },
  'chillicothegazette': {
    'displayName': 'Chillicothe Gazette',
    'baseUrl': 'chillicothegazette.com',
    'hostName': 'chillicothegazette',
    'region': 'Ohio',
  },
  'cincinnati': {
    'displayName': 'Cincinnati.com',
    'baseUrl': 'cincinnati.com',
    'hostName': 'cincinnati',
    'region': 'Ohio',
  },
  'citizen-times': {
    'displayName': 'Citizen Times',
    'baseUrl': 'citizen-times.com',
    'hostName': 'citizen-times',
    'region': 'Southeast',
  },
  'clarionledger': {
    'displayName': 'The Clarion Ledger',
    'baseUrl': 'clarionledger.com',
    'hostName': 'clarionledger',
    'region': 'Gulf',
  },
  'coloradoan': {
    'displayName': 'Coloradoan',
    'baseUrl': 'coloradoan.com',
    'hostName': 'coloradoan',
    'region': 'Plains',
  },
  'commercialappeal': {
    'displayName': 'The Commercial Appeal',
    'baseUrl': 'commercialappeal.com',
    'hostName': 'commercialappeal',
    'region': 'Tennessee',
  },
  'coshoctontribune': {
    'displayName': 'Coshocton Tribune',
    'baseUrl': 'coshoctontribune.com',
    'hostName': 'coshoctontribune',
    'region': 'Ohio',
  },
  'courier-journal': {
    'displayName': 'The Courier-Journal',
    'baseUrl': 'courier-journal.com',
    'hostName': 'courier-journal',
    'region': 'Midwest',
  },
  'courierpostonline': {
    'displayName': 'Courier-Post',
    'baseUrl': 'courierpostonline.com',
    'hostName': 'courierpostonline',
    'region': 'New Jersey',
  },
  'courierpress': {
    'displayName': 'Evansville Courier & Press',
    'baseUrl': 'courierpress.com',
    'hostName': 'courierpress',
    'region': 'Midwest',
  },
  'currentargus': {
    'displayName': 'Carlsbad Current Argus',
    'baseUrl': 'currentargus.com',
    'hostName': 'currentargus',
    'region': 'Southwest',
  },
  'daily-times': {
    'displayName': 'Farmington Daily Times',
    'baseUrl': 'daily-times.com',
    'hostName': 'daily-times',
    'region': 'Southwest',
  },
  'dailyrecord': {
    'displayName': 'Daily Record',
    'baseUrl': 'dailyrecord.com',
    'hostName': 'dailyrecord',
    'region': 'New Jersey',
  },
  'dailyworld': {
    'displayName': 'DailyWorld.com',
    'baseUrl': 'dailyworld.com',
    'hostName': 'dailyworld',
    'region': 'Gulf',
  },
  'delawarebeaches': {
    'displayName': 'Delaware Beaches',
    'baseUrl': 'delawarebeaches.com',
    'hostName': 'delawarebeaches',
    'region': 'Atlantic',
  },
  'delawareonline': {
    'displayName': 'delawareonline',
    'baseUrl': 'delawareonline.com',
    'hostName': 'delawareonline',
    'region': 'Atlantic',
  },
  'delmarvanow': {
    'displayName': 'Delmarva Daily Times',
    'baseUrl': 'delmarvanow.com',
    'hostName': 'delmarvanow',
    'region': 'Atlantic',
  },
  'demingheadlight': {
    'displayName': 'The Deming Headlight',
    'baseUrl': 'demingheadlight.com',
    'hostName': 'demingheadlight',
    'region': 'Southwest',
  },
  'democratandchronicle': {
    'displayName': 'Rochester Democrat and Chronicle',
    'baseUrl': 'democratandchronicle.com',
    'hostName': 'democratandchronicle',
    'region': 'Northeast',
  },
  'desertsun': {
    'displayName': 'Desert Sun',
    'baseUrl': 'desertsun.com',
    'hostName': 'desertsun',
    'region': 'Pacific',
  },
  'desmoinesregister': {
    'displayName': 'Des Moines Register',
    'baseUrl': 'desmoinesregister.com',
    'hostName': 'desmoinesregister',
    'region': 'Plains',
  },
  'detroitnews': {
    'displayName': 'Detroit News',
    'baseUrl': 'detroitnews.com',
    'hostName': 'detroitnews',
    'region': 'Midwest',
  },
  'dmjuice': {
    'displayName': 'Juice',
    'baseUrl': 'dmjuice.com',
    'hostName': 'dmjuice',
    'region': 'Plains',
  },
  'dnj': {
    'displayName': 'DNJ',
    'baseUrl': 'dnj.com',
    'hostName': 'dnj',
    'region': 'Tennessee',
  },
  'elpasotimes': {
    'displayName': 'El Paso Times',
    'baseUrl': 'elpasotimes.com',
    'hostName': 'elpasotimes',
    'region': 'Texas',
  },
  'elpasoymas': {
    'displayName': 'El Paso y Más',
    'baseUrl': 'elpasoymas.com',
    'hostName': 'elpasoymas',
    'region': 'Texas',
  },
  'eveningsun': {
    'displayName': 'The Evening Sun',
    'baseUrl': 'eveningsun.com',
    'hostName': 'eveningsun',
    'region': 'Atlantic',
  },
  'fdlreporter': {
    'displayName': 'Action Reporter Media',
    'baseUrl': 'fdlreporter.com',
    'hostName': 'fdlreporter',
    'region': 'Wisconsin',
  },
  'flipsidepa': {
    'displayName': 'FlipSidePA',
    'baseUrl': 'flipsidepa.com',
    'hostName': 'flipsidepa',
    'region': 'Atlantic',
  },
  'floridatoday': {
    'displayName': 'Florida Today',
    'baseUrl': 'floridatoday.com',
    'hostName': 'floridatoday',
    'region': 'Florida',
  },
  'freep': {
    'displayName': 'Detroit Free Press',
    'baseUrl': 'freep.com',
    'hostName': 'freep',
    'region': 'Midwest',
  },
  'fsunews': {
    'displayName': 'FSView & Florida Flambeau',
    'baseUrl': 'fsunews.com',
    'hostName': 'fsunews',
    'region': 'Florida',
  },
  'gametimepa': {
    'displayName': 'GameTimePA',
    'baseUrl': 'gametimepa.com',
    'hostName': 'gametimepa',
    'region': 'Atlantic',
  },
  'greatfallstribune': {
    'displayName': 'Great Falls Tribune',
    'baseUrl': 'greatfallstribune.com',
    'hostName': 'greatfallstribune',
    'region': 'Plains',
  },
  'greenbaypressgazette': {
    'displayName': 'Press Gazette Media',
    'baseUrl': 'greenbaypressgazette.com',
    'hostName': 'greenbaypressgazette',
    'region': 'Wisconsin',
  },
  'greenvilleonline': {
    'displayName': 'The Greenville News',
    'baseUrl': 'greenvilleonline.com',
    'hostName': 'greenvilleonline',
    'region': 'Southeast',
  },
  'guampdn': {
    'displayName': 'Pacific Daily News',
    'baseUrl': 'guampdn.com',
    'hostName': 'guampdn',
    'region': 'Pacific',
  },
  'hattiesburgamerican': {
    'displayName': 'Hattiesburg American',
    'baseUrl': 'hattiesburgamerican.com',
    'hostName': 'hattiesburgamerican',
    'region': 'Gulf',
  },
  'hawkcentral': {
    'displayName': 'Hawk Central',
    'baseUrl': 'hawkcentral.com',
    'hostName': 'hawkcentral',
    'region': 'Plains',
  },
  'hometownlife': {
    'displayName': 'HometownLife',
    'baseUrl': 'hometownlife.com',
    'hostName': 'hometownlife',
    'region': 'Midwest',
  },
  'htrnews': {
    'displayName': 'HTR Media',
    'baseUrl': 'htrnews.com',
    'hostName': 'htrnews',
    'region': 'Wisconsin',
  },
  'independentmail': {
    'displayName': 'Independent Mail',
    'baseUrl': 'independentmail.com',
    'hostName': 'independentmail',
    'region': 'Southeast',
  },
  'indystar': {
    'displayName': 'Indianapolis Star',
    'baseUrl': 'indystar.com',
    'hostName': 'indystar',
    'region': 'Midwest',
  },
  'ithacajournal': {
    'displayName': 'Ithaca Journal',
    'baseUrl': 'ithacajournal.com',
    'hostName': 'ithacajournal',
    'region': 'Northeast',
  },
  'jacksonsun': {
    'displayName': 'The Jackson Sun',
    'baseUrl': 'jacksonsun.com',
    'hostName': 'jacksonsun',
    'region': 'Tennessee',
  },
  'jconline': {
    'displayName': 'Journal and Courier',
    'baseUrl': 'jconline.com',
    'hostName': 'jconline',
    'region': 'Midwest',
  },
  'jsonline': {
    'displayName': 'Milwaukee Journal Sentinel',
    'baseUrl': 'jsonline.com',
    'hostName': 'jsonline',
    'region': 'Wisconsin',
  },
  'knoxnews': {
    'displayName': 'Knoxville News Sentinel',
    'baseUrl': 'knoxnews.com',
    'hostName': 'knoxnews',
    'region': 'Tennessee',
  },
  'lakecountrynow': {
    'displayName': 'Lake Country Now',
    'baseUrl': 'lakecountrynow.com',
    'hostName': 'lakecountrynow',
    'region': 'Wisconsin',
  },
  'lancastereaglegazette': {
    'displayName': 'Lancaster Eagle Gazette',
    'baseUrl': 'lancastereaglegazette.com',
    'hostName': 'lancastereaglegazette',
    'region': 'Ohio',
  },
  'lansingstatejournal': {
    'displayName': 'Lansing State Journal',
    'baseUrl': 'lansingstatejournal.com',
    'hostName': 'lansingstatejournal',
    'region': 'Midwest',
  },
  'lavozarizona': {
    'displayName': 'Lavoz',
    'baseUrl': 'lavozarizona.com',
    'hostName': 'lavozarizona',
    'region': 'Southwest',
  },
  'lcsun-news': {
    'displayName': 'Las Cruces Sun-News',
    'baseUrl': 'lcsun-news.com',
    'hostName': 'lcsun-news',
    'region': 'Southwest',
  },
  'ldnews': {
    'displayName': 'Lebanon Daily News',
    'baseUrl': 'ldnews.com',
    'hostName': 'ldnews',
    'region': 'Atlantic',
  },
  'livingstondaily': {
    'displayName': 'Livingston Daily Press & Argus',
    'baseUrl': 'livingstondaily.com',
    'hostName': 'livingstondaily',
    'region': 'Midwest',
  },
  'lohud': {
    'displayName': 'lohud.com',
    'baseUrl': 'lohud.com',
    'hostName': 'lohud',
    'region': 'Northeast',
  },
  'mansfieldnewsjournal': {
    'displayName': 'Mansfield News Journal',
    'baseUrl': 'mansfieldnewsjournal.com',
    'hostName': 'mansfieldnewsjournal',
    'region': 'Ohio',
  },
  'marcoislandflorida': {
    'displayName': 'Marco Island Sun Times',
    'baseUrl': 'marcoislandflorida.com',
    'hostName': 'marcoislandflorida',
    'region': 'Florida',
  },
  'marionstar': {
    'displayName': 'Marion Star',
    'baseUrl': 'marionstar.com',
    'hostName': 'marionstar',
    'region': 'Ohio',
  },
  'marshfieldnewsherald': {
    'displayName': 'News-Herald Media',
    'baseUrl': 'marshfieldnewsherald.com',
    'hostName': 'marshfieldnewsherald',
    'region': 'Wisconsin',
  },
  'metroparentmagazine': {
    'displayName': 'Metro Parent Magazine',
    'baseUrl': 'metroparentmagazine.com',
    'hostName': 'metroparentmagazine',
    'region': 'Wisconsin',
  },
  'montgomeryadvertiser': {
    'displayName': 'The Montgomery Advertiser',
    'baseUrl': 'montgomeryadvertiser.com',
    'hostName': 'montgomeryadvertiser',
    'region': 'Gulf',
  },
  'mycentraljersey': {
    'displayName': 'MY CENTRAL JERSEY',
    'baseUrl': 'mycentraljersey.com',
    'hostName': 'mycentraljersey',
    'region': 'New Jersey',
  },
  'mynorthshorenow': {
    'displayName': 'My North Shore Now',
    'baseUrl': 'mynorthshorenow.com',
    'hostName': 'mynorthshorenow',
    'region': 'Wisconsin',
  },
  'naplesnews': {
    'displayName': 'Naples Daily News',
    'baseUrl': 'naplesnews.com',
    'hostName': 'naplesnews',
    'region': 'Florida',
  },
  'newarkadvocate': {
    'displayName': 'The Newark Advocate',
    'baseUrl': 'newarkadvocate.com',
    'hostName': 'newarkadvocate',
    'region': 'Ohio',
  },
  'news-leader': {
    'displayName': 'Springfield News-Leader',
    'baseUrl': 'news-leader.com',
    'hostName': 'news-leader',
    'region': 'Plains',
  },
  'news-press': {
    'displayName': 'The News-Press',
    'baseUrl': 'news-press.com',
    'hostName': 'news-press',
    'region': 'Florida',
  },
  'newsleader': {
    'displayName': 'The News Leader',
    'baseUrl': 'newsleader.com',
    'hostName': 'newsleader',
    'region': 'Southeast',
  },
  'northjersey': {
    'displayName': 'North Jersey',
    'baseUrl': 'northjersey.com',
    'hostName': 'northjersey',
    'region': 'New Jersey',
  },
  'packersnews': {
    'displayName': 'Packers News',
    'baseUrl': 'packersnews.com',
    'hostName': 'packersnews',
    'region': 'Wisconsin',
  },
  'pal-item': {
    'displayName': 'Pal-Item',
    'baseUrl': 'pal-item.com',
    'hostName': 'pal-item',
    'region': 'Midwest',
  },
  'pnj': {
    'displayName': 'Pensacola News Journal',
    'baseUrl': 'pnj.com',
    'hostName': 'pnj',
    'region': 'Florida',
  },
  'portclintonnewsherald': {
    'displayName': 'Port Clinton News Herald',
    'baseUrl': 'portclintonnewsherald.com',
    'hostName': 'portclintonnewsherald',
    'region': 'Ohio',
  },
  'postcrescent': {
    'displayName': 'Post-Crescent Media',
    'baseUrl': 'postcrescent.com',
    'hostName': 'postcrescent',
    'region': 'Wisconsin',
  },
  'poughkeepsiejournal': {
    'displayName': 'The Poughkeepsie Journal',
    'baseUrl': 'poughkeepsiejournal.com',
    'hostName': 'poughkeepsiejournal',
    'region': 'Northeast',
  },
  'press-citizen': {
    'displayName': 'Iowa City Press-Citizen',
    'baseUrl': 'press-citizen.com',
    'hostName': 'press-citizen',
    'region': 'Plains',
  },
  'pressconnects': {
    'displayName': 'Pressconnects',
    'baseUrl': 'pressconnects.com',
    'hostName': 'pressconnects',
    'region': 'Northeast',
  },
  'publicopiniononline': {
    'displayName': 'Public Opinion Online',
    'baseUrl': 'publicopiniononline.com',
    'hostName': 'publicopiniononline',
    'region': 'Atlantic',
  },
  'reno': {
    'displayName': 'Reno.com',
    'baseUrl': 'reno.com',
    'hostName': 'reno',
    'region': 'Pacific',
  },
  'rgj': {
    'displayName': 'Reno Gazette Journal',
    'baseUrl': 'rgj.com',
    'hostName': 'rgj',
    'region': 'Pacific',
  },
  'ruidosonews': {
    'displayName': 'Ruidoso News',
    'baseUrl': 'ruidosonews.com',
    'hostName': 'ruidosonews',
    'region': 'Southwest',
  },
  'scsun-news': {
    'displayName': 'Silver City Sun-News',
    'baseUrl': 'scsun-news.com',
    'hostName': 'scsun-news',
    'region': 'Southwest',
  },
  'sctimes': {
    'displayName': 'St. Cloud Times',
    'baseUrl': 'sctimes.com',
    'hostName': 'sctimes',
    'region': 'Plains',
  },
  'sheboyganpress': {
    'displayName': 'Sheboygan Press Media',
    'baseUrl': 'sheboyganpress.com',
    'hostName': 'sheboyganpress',
    'region': 'Wisconsin',
  },
  'shreveporttimes': {
    'displayName': 'shreveporttimes.com',
    'baseUrl': 'shreveporttimes.com',
    'hostName': 'shreveporttimes',
    'region': 'Gulf',
  },
  'stargazette': {
    'displayName': 'Elmira Star-Gazette',
    'baseUrl': 'stargazette.com',
    'hostName': 'stargazette',
    'region': 'Northeast',
  },
  'statesmanjournal': {
    'displayName': 'Statesman Journal',
    'baseUrl': 'statesmanjournal.com',
    'hostName': 'statesmanjournal',
    'region': 'Pacific',
  },
  'stevenspointjournal': {
    'displayName': 'Stevens Point Journal Media',
    'baseUrl': 'stevenspointjournal.com',
    'hostName': 'stevenspointjournal',
    'region': 'Wisconsin',
  },
  'tallahassee': {
    'displayName': 'Tallahassee Democrat',
    'baseUrl': 'tallahassee.com',
    'hostName': 'tallahassee',
    'region': 'Florida',
  },
  'tcpalm': {
    'displayName': 'TCPalm',
    'baseUrl': 'tcpalm.com',
    'hostName': 'tcpalm',
    'region': 'Florida',
  },
  'tennessean': {
    'displayName': 'The Tennessean',
    'baseUrl': 'tennessean.com',
    'hostName': 'tennessean',
    'region': 'Tennessee',
  },
  'theadvertiser': {
    'displayName': 'The Advertiser',
    'baseUrl': 'theadvertiser.com',
    'hostName': 'theadvertiser',
    'region': 'Gulf',
  },
  'thecalifornian': {
    'displayName': 'The Salinas Californian',
    'baseUrl': 'thecalifornian.com',
    'hostName': 'thecalifornian',
    'region': 'Pacific',
  },
  'thedailyjournal': {
    'displayName': 'The Daily Journal',
    'baseUrl': 'thedailyjournal.com',
    'hostName': 'thedailyjournal',
    'region': 'New Jersey',
  },
  'thegleaner': {
    'displayName': 'The Gleaner',
    'baseUrl': 'thegleaner.com',
    'hostName': 'thegleaner',
    'region': 'Midwest',
  },
  'thehammontonnews': {
    'displayName': 'The Hammonton News',
    'baseUrl': 'thehammontonnews.com',
    'hostName': 'thehammontonnews',
    'region': 'New Jersey',
  },
  'theleafchronicle': {
    'displayName': 'The Leaf Chronicle',
    'baseUrl': 'theleafchronicle.com',
    'hostName': 'theleafchronicle',
    'region': 'Tennessee',
  },
  'thenews-messenger': {
    'displayName': 'The News-Messenger',
    'baseUrl': 'thenews-messenger.com',
    'hostName': 'thenews-messenger',
    'region': 'Ohio',
  },
  'thenewsstar': {
    'displayName': 'thenewsstar.com',
    'baseUrl': 'thenewsstar.com',
    'hostName': 'thenewsstar',
    'region': 'Gulf',
  },
  'thenorthwestern': {
    'displayName': 'Northwestern Media',
    'baseUrl': 'thenorthwestern.com',
    'hostName': 'thenorthwestern',
    'region': 'Wisconsin',
  },
  'thespectrum': {
    'displayName': 'The Spectrum & Daily News',
    'baseUrl': 'thespectrum.com',
    'hostName': 'thespectrum',
    'region': 'Southwest',
  },
  'thestarpress': {
    'displayName': 'TheStarPress',
    'baseUrl': 'thestarpress.com',
    'hostName': 'thestarpress',
    'region': 'Midwest',
  },
  'thetimesherald': {
    'displayName': 'The Times Herald',
    'baseUrl': 'thetimesherald.com',
    'hostName': 'thetimesherald',
    'region': 'Midwest',
  },
  'thetowntalk': {
    'displayName': 'thetowntalk.com',
    'baseUrl': 'thetowntalk.com',
    'hostName': 'thetowntalk',
    'region': 'Gulf',
  },
  'upstateparent': {
    'displayName': 'Upstate Parent',
    'baseUrl': 'upstateparent.com',
    'hostName': 'upstateparent',
    'region': 'Southeast',
  },
  'usatoday': {
    'displayName': 'USA TODAY',
    'baseUrl': 'usatoday.com',
    'hostName': 'usatoday',
    'region': 'USA',
  },
  'vcstar': {
    'displayName': 'Ventura County Star',
    'baseUrl': 'vcstar.com',
    'hostName': 'vcstar',
    'region': 'Pacific',
  },
  'visaliatimesdelta': {
    'displayName': 'Visalia Times-Delta and Tulare Advance-Register',
    'baseUrl': 'visaliatimesdelta.com',
    'hostName': 'visaliatimesdelta',
    'region': 'Pacific',
  },
  'waukeshanow': {
    'displayName': 'Waukesha Now',
    'baseUrl': 'waukeshanow.com',
    'hostName': 'waukeshanow',
    'region': 'Wisconsin',
  },
  'wausaudailyherald': {
    'displayName': 'Daily Herald Media',
    'baseUrl': 'wausaudailyherald.com',
    'hostName': 'wausaudailyherald',
    'region': 'Wisconsin',
  },
  'wauwatosanow': {
    'displayName': 'Wauwatosa Now',
    'baseUrl': 'wauwatosanow.com',
    'hostName': 'wauwatosanow',
    'region': 'Wisconsin',
  },
  'wisconsinrapidstribune': {
    'displayName': 'Daily Tribune Media',
    'baseUrl': 'wisconsinrapidstribune.com',
    'hostName': 'wisconsinrapidstribune',
    'region': 'Wisconsin',
  },
  'wisfarmer': {
    'displayName': 'Wisconsin State Farmer',
    'baseUrl': 'wisfarmer.com',
    'hostName': 'wisfarmer',
    'region': 'Wisconsin',
  },
  'ydr': {
    'displayName': 'The York Daily Record',
    'baseUrl': 'ydr.com',
    'hostName': 'ydr',
    'region': 'Atlantic',
  },
  'yorkdispatch': {
    'displayName': 'York Dispatch',
    'baseUrl': 'yorkdispatch.com',
    'hostName': 'yorkdispatch',
    'region': 'Atlantic',
  },
  'zanesvilletimesrecorder': {
    'displayName': 'Zanesville Times Recorder',
    'baseUrl': 'zanesvilletimesrecorder.com',
    'hostName': 'zanesvilletimesrecorder',
    'region': 'Ohio',
  },
};
